### ISSUE TITLE
Make some tests to determine the data flow from esp's

### ISSUE THREAD

**Issue by fuzoh** [museebolo/climat_guardian#11]
Would be interesting to know the amount of data created in the db from the ESPs to anticipate future hardware needs.

We can predict the main part of the data flow. If we know the amount of ESP and the data acquisition frequency.

**Comment by Rignchen** [comment]
In the past few days, the esp have register between 1411 and 1504 entries per day

**Comment by fuzoh** [comment]
Okay, now check the disk usage to determine the average consumption of memory for 1 year

**Comment by Rignchen** [comment]
currently there's a total of 66782 entries in the data table, the database's folder weight 69MiB
there's not only the data table but the other tables aren't as full as the data one, I don't think they are significant enough
witch mean that 1 entire weight ~ 1080 Bytes

Over 1 day with 1440 entries, we use ~1.6 MB and ~0.57 GB over 1 year

However, we are currently storing the ip address as a varchar(15) and are planing on changing it for a foreign key witch should reduce the weight of each entries

**Comment by Alex-zReeZ** [comment]
The last measure was wrong because the weight of the database is completely different from the data table.

Currently, there's a total of 52559 entries in the data table and weight 6544KB.
Which means that one entry weight ~125 Bytes, in one day (1440 entry) ~179 KB, and ~65.5 MB a year

**Comment by fuzoh** [comment]
You can use \l command to obtain database information with size https://www.postgresql.org/docs/current/app-psql.html
