### ISSUE TITLE
Fix readme installation instructions

### ISSUE THREAD

**Issue by Alex-zReeZ** [museebolo/climat_guardian#120]
in the read me, after cloning the repo, it says you should do 

cd climate-guardian

but it should say

cd climate_guardian

**Comment by fuzoh** [comment]
The installation instructions needs to be improved.

I think the reader needs only instruction to deploy the solution. The instructions to setup the dev environment can pe separated in a more technical documentation. In the `docs` folder.

**Comment by ColinRgm** [comment]
Estimate 1h
